// <auto-generated />
namespace GithubWebService.Migrations.GithubDataPart2Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class test2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test2));
        
        string IMigrationMetadata.Id
        {
            get { return "201805050320554_test2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
