// <auto-generated />
namespace GithubWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class enas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enas));
        
        string IMigrationMetadata.Id
        {
            get { return "201804110721397_enas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
